"""Customer

Revision ID: 7c2421bbf9af
Revises: 5028e17d1f42
Create Date: 2022-11-29 19:15:49.425121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2421bbf9af'
down_revision = '5028e17d1f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namn', sa.String(length=80), nullable=False),
    sa.Column('telefonnummer', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
